version: '3.3'
services:

  fluentd:
    depends_on:
    - elasticsearch
    build: ./efk/fluentd
    volumes:
      - ./efk/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "5140:5140"

  elasticsearch:
    image: elasticsearch
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    depends_on:
    - elasticsearch
    image: kibana
    # image: docker.elastic.co/kibana/kibana:6.3.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  cartpole:
    depends_on:
      - elasticsearch
      - kibana
    build: ../
    image: hypnosapos/${DOCKER_IMAGE:-cartpole-rl-remote}:${DOCKER_TAG:-latest}
    command: >-
      cartpole --log-level DEBUG -e ${TRAIN_EPISODES:-200}
      train --gamma 0.095 0.099 0.001 --batch_size 32 33 -f /tmp/models/cartpole-rl-remote
    volumes:
    - ../.models:/tmp/models
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: cartpole