apiVersion: v1
kind: PersistentVolume
metadata:
  name: polyaxon-pv-outputs
  labels:
    app: polyaxon
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFS_HOST  # Use the right IP
    path: "/data/outputs"
  claimRef:
    namespace: polyaxon 
    name: polyaxon-pvc-outputs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: polyaxon-pvc-outputs
  namespace: polyaxon
  labels:
    app: polyaxon
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
